webtalk_init -webtalk_dir /home/it/rv32imf/jtag_pd_verif/vivado_proj/vivado_proj.sim/sim_1/behav/xsim/xsim.dir/rv32i_soc_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Jul 10 07:50:29 2025" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2552052" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "1779ef0f-ab73-4417-af67-fb0a6a1f573d" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "3d2a86cd729c4f488f97d0c2e812bd09" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "170" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 24.04.2 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "13th Gen Intel(R) Core(TM) i7-1370P" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1494.232 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "33.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key SystemVerilog -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key File_Counter -value "74" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "1225 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "149 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "2510" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "268" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip unimacro_ver unisims_ver " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "2.78_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "452244_KB" -context "xsim\\usage"
webtalk_transmit -clientid 358701581 -regid "" -xml /home/it/rv32imf/jtag_pd_verif/vivado_proj/vivado_proj.sim/sim_1/behav/xsim/xsim.dir/rv32i_soc_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/it/rv32imf/jtag_pd_verif/vivado_proj/vivado_proj.sim/sim_1/behav/xsim/xsim.dir/rv32i_soc_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/it/rv32imf/jtag_pd_verif/vivado_proj/vivado_proj.sim/sim_1/behav/xsim/xsim.dir/rv32i_soc_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
