
## Corner values
set TEMP_BC 0.0
set TEMP_TC 25.0
set TEMP_WC 125

set V_VDD_BC 1.98
set V_VDD_TC 1.8
set V_VDD_WC 1.62

set V_VSS 0.0

set V_IOVDD_BC 3.0
set V_IOVDD_TC 3.3
set V_IOVDD_WC 3.6

set TIMING_DERATE_BEST_EARLY 0.95
set TIMING_DERATE_TYPICAL_LATE 1.05
set TIMING_DERATE_WORST_LATE 1.1

set FAST_VIRTUAL_CLOCK_NAME vclk
set FAST_CLOCK_NAME CLK
set FAST_CLOCK_PERIOD 10000

set CLOCK_UNCERTAINTY_FAST_CLOCK_BEST 150
set CLOCK_UNCERTAINTY_FAST_CLOCK_TYPICAL 200
set CLOCK_UNCERTAINTY_FAST_CLOCK_WORST 250

set CLOCK_LATENCY_FAST_CLOCK_BEST_MAX 800
set CLOCK_LATENCY_FAST_CLOCK_TYPICAL_MAX 900
set CLOCK_LATENCY_FAST_CLOCK_WORST_MAX 1000
# set CLOCK_LATENCY_FAST_CLOCK_BEST_MAX 4000
# set CLOCK_LATENCY_FAST_CLOCK_TYPICAL_MAX 5000
# set CLOCK_LATENCY_FAST_CLOCK_WORST_MAX 6000

set CLOCK_LATENCY_FAST_CLOCK_BEST_MIN 800
set CLOCK_LATENCY_FAST_CLOCK_TYPICAL_MIN 900
set CLOCK_LATENCY_FAST_CLOCK_WORST_MIN 1000
# set CLOCK_LATENCY_FAST_CLOCK_BEST_MIN 3500
# set CLOCK_LATENCY_FAST_CLOCK_TYPICAL_MIN 4500
# set CLOCK_LATENCY_FAST_CLOCK_WORST_MIN 5500

set INPUT_DELAY_FAST_CLOCK_BEST_MAX 1500
set INPUT_DELAY_FAST_CLOCK_TYPICAL_MAX 2000
set INPUT_DELAY_FAST_CLOCK_WORST_MAX 2500

set INPUT_DELAY_FAST_CLOCK_BEST_MIN 0.0
set INPUT_DELAY_FAST_CLOCK_TYPICAL_MIN 0.0
set INPUT_DELAY_FAST_CLOCK_WORST_MIN 0.0

set OUTPUT_DELAY_FAST_CLOCK_BEST_MIN 0.0
set OUTPUT_DELAY_FAST_CLOCK_TYPICAL_MIN 0.0
set OUTPUT_DELAY_FAST_CLOCK_WORST_MIN 0.0

set OUTPUT_DELAY_FAST_CLOCK_BEST_MAX 1500
set OUTPUT_DELAY_FAST_CLOCK_TYPICAL_MAX 2000
set OUTPUT_DELAY_FAST_CLOCK_WORST_MAX 2500

set MAX_TRANSITION_FAST_CLOCK_BEST 500
set MAX_TRANSITION_FAST_CLOCK_TYPICAL 1000
set MAX_TRANSITION_FAST_CLOCK_WORST 1500

set MAX_TRANSITION_DATA_FAST_CLOCK_BEST 1000
set MAX_TRANSITION_DATA_FAST_CLOCK_TYPICAL 1500
set MAX_TRANSITION_DATA_FAST_CLOCK_WORST 2000

set MAX_CAPACITANCE_FAST_CLOCK_BEST 500
set MAX_CAPACITANCE_FAST_CLOCK_TYPICAL 650
set MAX_CAPACITANCE_FAST_CLOCK_WORST 800

set LOAD_BEST 4000
set LOAD_TYPICAL 5000
set LOAD_WORST 6000