#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Sat Jul 05 10:31:03 +03 2025
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 1b9f1b1a3be140d793d857660e6133b8 --incr --debug typical --relax --mt 8 -d "VIVADO_SIM=" -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot rv32i_soc_tb_behav xil_defaultlib.rv32i_soc_tb xil_defaultlib.glbl -log elaborate.log"
xelab -wto 1b9f1b1a3be140d793d857660e6133b8 --incr --debug typical --relax --mt 8 -d "VIVADO_SIM=" -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot rv32i_soc_tb_behav xil_defaultlib.rv32i_soc_tb xil_defaultlib.glbl -log elaborate.log

